export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
export const OFFSET_LOADING = 'OFFSET_LOADING'
export const HIDE_OFFSET_LOADING = 'HIDE_OFFSET_LOADING'

export const GET_ASSETS = 'GET_ASSETS'
export const GET_SINGLE_ASSET = 'GET_SINGLE_ASSET'
export const START_INDEX = 'START_INDEX'
export const GET_OFFSET_DATA = 'GET_OFFSET_DATA'

export const CHECK_CELO = 'CHECK_CELO'
export const LOGIN_CELO_WALLET = 'LOGIN_CELO_WALLET'
export const READ_CELO_CONTRACT = 'READ_CELO_CONTRACT'
export const WRITE_CELO_CONTRACT = 'WRITE_CELO_CONTRACT'
export const THEME_SAVE = 'THEME_SAVE'

export const GET_IMAGE = 'GET_IMAGE'
export const GET_PERMISSIONS = 'GET_PERMISSIONS'
export const CLEAR_SELECTED_IMAGE = 'CLEAR_SELECTED_IMAGE'

export const DEPLOY_NFT_CONTRACT = 'DEPLOY_NFT_CONTRACT'

